import requests
from deepdiff import DeepDiff

tokenid = range(6, 10)
prev = []
for t_id in tokenid:
    URL = f"https://api.opensea.io/api/v1/asset/0xed5af388653567af2f388e6224dc7c4b3241c544/{t_id}/?account_address=0xed5af388653567af2f388e6224dc7c4b3241c544&include_orders=false"
    headers = {"X-API-KEY": "9fc6e5182bf84787b365cde911a77a56"}
    response = requests.get(URL, headers=headers)
    response_json = response.json()
    azuki_traits = response_json["traits"]
    diff = DeepDiff(azuki_traits, prev)
    print(diff.pretty())
    prev = azuki_traits


[
    [
        {
            "trait_type": "Type",
            "value": "Human",
            "display_type": None,
            "max_value": None,
            "trait_count": 9018,
            "order": None,
        },
        {
            "trait_type": "Background",
            "value": "Off White D",
            "display_type": None,
            "max_value": None,
            "trait_count": 1990,
            "order": None,
        },
        {
            "trait_type": "Mouth",
            "value": "Lipstick",
            "display_type": None,
            "max_value": None,
            "trait_count": 408,
            "order": None,
        },
        {
            "trait_type": "Eyes",
            "value": "Daydreaming",
            "display_type": None,
            "max_value": None,
            "trait_count": 387,
            "order": None,
        },
        {
            "trait_type": "Hair",
            "value": "Pink Hairband",
            "display_type": None,
            "max_value": None,
            "trait_count": 77,
            "order": None,
        },
        {
            "trait_type": "Clothing",
            "value": "White Qipao with Fur",
            "display_type": None,
            "max_value": None,
            "trait_count": 84,
            "order": None,
        },
        {
            "trait_type": "Offhand",
            "value": "Gloves",
            "display_type": None,
            "max_value": None,
            "trait_count": 111,
            "order": None,
        },
    ],
    [
        {
            "trait_type": "Type",
            "value": "Human",
            "display_type": None,
            "max_value": None,
            "trait_count": 9018,
            "order": None,
        },
        {
            "trait_type": "Background",
            "value": "Red",
            "display_type": None,
            "max_value": None,
            "trait_count": 1006,
            "order": None,
        },
        {
            "trait_type": "Eyes",
            "value": "Ruby",
            "display_type": None,
            "max_value": None,
            "trait_count": 381,
            "order": None,
        },
        {
            "trait_type": "Mouth",
            "value": "Chewing",
            "display_type": None,
            "max_value": None,
            "trait_count": 351,
            "order": None,
        },
        {
            "trait_type": "Hair",
            "value": "Pink Flowy",
            "display_type": None,
            "max_value": None,
            "trait_count": 87,
            "order": None,
        },
        {
            "trait_type": "Ear",
            "value": "Red Tassel",
            "display_type": None,
            "max_value": None,
            "trait_count": 33,
            "order": None,
        },
        {
            "trait_type": "Clothing",
            "value": "Vest",
            "display_type": None,
            "max_value": None,
            "trait_count": 160,
            "order": None,
        },
    ],
]
[
    [
        {
            "trait_type": "Type",
            "value": "Human",
            "display_type": None,
            "max_value": None,
            "trait_count": 9018,
            "order": None,
        },
        {
            "trait_type": "Background",
            "value": "Off White D",
            "display_type": None,
            "max_value": None,
            "trait_count": 1990,
            "order": None,
        },
        {
            "trait_type": "Mouth",
            "value": "Lipstick",
            "display_type": None,
            "max_value": None,
            "trait_count": 408,
            "order": None,
        },
        {
            "trait_type": "Eyes",
            "value": "Daydreaming",
            "display_type": None,
            "max_value": None,
            "trait_count": 387,
            "order": None,
        },
        {
            "trait_type": "Hair",
            "value": "Pink Hairband",
            "display_type": None,
            "max_value": None,
            "trait_count": 77,
            "order": None,
        },
        {
            "trait_type": "Clothing",
            "value": "White Qipao with Fur",
            "display_type": None,
            "max_value": None,
            "trait_count": 84,
            "order": None,
        },
        {
            "trait_type": "Offhand",
            "value": "Gloves",
            "display_type": None,
            "max_value": None,
            "trait_count": 111,
            "order": None,
        },
    ],
    [
        {
            "trait_type": "Type",
            "value": "Human",
            "display_type": None,
            "max_value": None,
            "trait_count": 9018,
            "order": None,
        },
        {
            "trait_type": "Background",
            "value": "Red",
            "display_type": None,
            "max_value": None,
            "trait_count": 1006,
            "order": None,
        },
        {
            "trait_type": "Eyes",
            "value": "Ruby",
            "display_type": None,
            "max_value": None,
            "trait_count": 381,
            "order": None,
        },
        {
            "trait_type": "Mouth",
            "value": "Chewing",
            "display_type": None,
            "max_value": None,
            "trait_count": 351,
            "order": None,
        },
        {
            "trait_type": "Hair",
            "value": "Pink Flowy",
            "display_type": None,
            "max_value": None,
            "trait_count": 87,
            "order": None,
        },
        {
            "trait_type": "Ear",
            "value": "Red Tassel",
            "display_type": None,
            "max_value": None,
            "trait_count": 33,
            "order": None,
        },
        {
            "trait_type": "Clothing",
            "value": "Vest",
            "display_type": None,
            "max_value": None,
            "trait_count": 160,
            "order": None,
        },
    ],
]
[
    {
        "trait_type": "Type",
        "value": "Human",
        "display_type": None,
        "max_value": None,
        "trait_count": 9018,
        "order": None,
    },
    {
        "trait_type": "Background",
        "value": "Off White D",
        "display_type": None,
        "max_value": None,
        "trait_count": 1990,
        "order": None,
    },
    {
        "trait_type": "Mouth",
        "value": "Lipstick",
        "display_type": None,
        "max_value": None,
        "trait_count": 408,
        "order": None,
    },
    {
        "trait_type": "Eyes",
        "value": "Daydreaming",
        "display_type": None,
        "max_value": None,
        "trait_count": 387,
        "order": None,
    },
    {
        "trait_type": "Hair",
        "value": "Pink Hairband",
        "display_type": None,
        "max_value": None,
        "trait_count": 77,
        "order": None,
    },
    {
        "trait_type": "Clothing",
        "value": "White Qipao with Fur",
        "display_type": None,
        "max_value": None,
        "trait_count": 84,
        "order": None,
    },
    {
        "trait_type": "Offhand",
        "value": "Gloves",
        "display_type": None,
        "max_value": None,
        "trait_count": 111,
        "order": None,
    },
]
[
    {
        "trait_type": "Type",
        "value": "Human",
        "display_type": None,
        "max_value": None,
        "trait_count": 9018,
        "order": None,
    },
    {
        "trait_type": "Background",
        "value": "Red",
        "display_type": None,
        "max_value": None,
        "trait_count": 1006,
        "order": None,
    },
    {
        "trait_type": "Eyes",
        "value": "Ruby",
        "display_type": None,
        "max_value": None,
        "trait_count": 381,
        "order": None,
    },
    {
        "trait_type": "Mouth",
        "value": "Chewing",
        "display_type": None,
        "max_value": None,
        "trait_count": 351,
        "order": None,
    },
    {
        "trait_type": "Hair",
        "value": "Pink Flowy",
        "display_type": None,
        "max_value": None,
        "trait_count": 87,
        "order": None,
    },
    {
        "trait_type": "Ear",
        "value": "Red Tassel",
        "display_type": None,
        "max_value": None,
        "trait_count": 33,
        "order": None,
    },
    {
        "trait_type": "Clothing",
        "value": "Vest",
        "display_type": None,
        "max_value": None,
        "trait_count": 160,
        "order": None,
    },
]
[
    {
        "trait_type": "Type",
        "value": "Human",
        "display_type": None,
        "max_value": None,
        "trait_count": 9018,
        "order": None,
    },
    {
        "trait_type": "Background",
        "value": "Red",
        "display_type": None,
        "max_value": None,
        "trait_count": 1006,
        "order": None,
    },
    {
        "trait_type": "Mouth",
        "value": "Grass",
        "display_type": None,
        "max_value": None,
        "trait_count": 390,
        "order": None,
    },
    {
        "trait_type": "Hair",
        "value": "Green Spiky",
        "display_type": None,
        "max_value": None,
        "trait_count": 117,
        "order": None,
    },
    {
        "trait_type": "Offhand",
        "value": "Katana",
        "display_type": None,
        "max_value": None,
        "trait_count": 439,
        "order": None,
    },
    {
        "trait_type": "Eyes",
        "value": "Careless",
        "display_type": None,
        "max_value": None,
        "trait_count": 381,
        "order": None,
    },
    {
        "trait_type": "Clothing",
        "value": "Green Yukata",
        "display_type": None,
        "max_value": None,
        "trait_count": 208,
        "order": None,
    },
    {
        "trait_type": "Neck",
        "value": "Frog Headphones",
        "display_type": None,
        "max_value": None,
        "trait_count": 52,
        "order": None,
    },
    {
        "trait_type": "Headgear",
        "value": "Frog Headband",
        "display_type": None,
        "max_value": None,
        "trait_count": 94,
        "order": None,
    },
]
[
    {
        "trait_type": "Type",
        "value": "Human",
        "display_type": None,
        "max_value": None,
        "trait_count": 9018,
        "order": None,
    },
    {
        "trait_type": "Background",
        "value": "Off White D",
        "display_type": None,
        "max_value": None,
        "trait_count": 1990,
        "order": None,
    },
    {
        "trait_type": "Mouth",
        "value": "Smirk",
        "display_type": None,
        "max_value": None,
        "trait_count": 726,
        "order": None,
    },
    {
        "trait_type": "Hair",
        "value": "Brown Dreadlocks",
        "display_type": None,
        "max_value": None,
        "trait_count": 21,
        "order": None,
    },
    {
        "trait_type": "Offhand",
        "value": "Katana",
        "display_type": None,
        "max_value": None,
        "trait_count": 439,
        "order": None,
    },
    {
        "trait_type": "Clothing",
        "value": "White Qipao with Fur",
        "display_type": None,
        "max_value": None,
        "trait_count": 84,
        "order": None,
    },
    {
        "trait_type": "Eyes",
        "value": "Lightning",
        "display_type": None,
        "max_value": None,
        "trait_count": 46,
        "order": None,
    },
]
